package com.example.weatherconsultationapp.openweathermap

enum class ParametersEnum {

    //
    PARAMETERSWITHLOCALIZATIONCOUNTRYCODEAPIKEY, PARAMETERSWITHLOCALIZATIONAPIKEY, PARAMETERSWITHLATITUDELONGITUDE
}